### PR TITLE
Use ng-if instead of ng-class for easier DOM rendering

### PR DESCRIPTION
**Pull request by maaso**

### CODE REVIEW

**Comment by mathieuales** [comment]
Thanks for sharing !
I'm using `ng-class` because i planned to make some animations on open/hide resources/operations ...

**Comment by maaso** [comment]
Ah I see.. could't ng-if's ng-enter and ng-leave events be used for the animation as well?

**Comment by mathieuales** [comment]
You're completely right !
I've never seen the issue you describe, do you have a huge swagger descriptor ?

**Comment by maaso** [comment]
Around 10k lines :)

**Pull request merged**
