### PR TITLE
Resolved issue relating to basepath containing '/'

### PR DESCRIPTION
**Pull request by daniel-cotton**
Issue number: #46 

Resolved issue relating to basepath containing '/' and leading to duplication of forward slashes (/) in try-me URL.

### CODE REVIEW

**Comment by daniel-cotton** [comment]
Improved fix - any trailing slashes are removed if applicable.

**Comment by mathieuales** [comment]
Hi !

Thanks for sharing !
Could you please make it a little bit more compact ?
`swagger.basePath.substring(swagger.basePath.length - 1) === '/' ? swagger.basePath.slice(0, -1) : swagger.basePath`
Your fix does not take into account that `basePath` can be null or empty as it was done before ...

Regards

**Comment by daniel-cotton** [comment]
Hi @mathieuales,

Thanks for the feedback! I've incorporated your changes & added a quick null/undefined check.

Thanks,
Dan

**Comment by anil2** [comment]
@daniel-cotton  @mathieuales  hi, I see that the problem with basepath is resolved in source, but the packages downloaded via bower still have the old version. Is there any plan to release the changed source code?

**Comment by anil-kk** [comment]
It looks like the problem is partially solved, I pulled a new request, When will be a new version released ? I still have older versions when I get the packages using Bower

**Comment by mathieuales** [comment]
Hi !
I'm working on other stuffs, a new release including the fix will come soon

**Pull request merged**
